# Generated by Django 4.1.7 on 2023-04-01 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import films.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('video', models.FileField(upload_to='videos/', validators=[films.validators.validate_file_extension])),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserFilmRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'Ok'), (2, 'Fine'), (3, 'Good'), (4, 'Cool'), (5, 'Very Good')])),
                ('in_bookmarks', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
        ),
    ]
