# Generated by Django 4.1.7 on 2023-04-03 13:58

from django.db import migrations, models
import django.db.models.deletion
import films.validators


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_category_alter_film_author_alter_film_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='about',
            field=models.CharField(max_length=255, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='film',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='film',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', validators=[films.validators.validate_file_extension], verbose_name='Видеофайл'),
        ),
    ]
